export enum TypeContrat {
  CDI = 'CDI',
  CDD = 'CDD',
  FREELANCE = 'FREELANCE',
  ALTERNANCE = 'ALTERNANCE',
  CIVP = 'CIVP',
  STAGE = 'STAGE',
}




export enum InterviewMode {
  TELEPHONIQUE = 'TELEPHONIQUE',
  PRESENTIEL = 'PRESENTIEL',
  DISTANCIEL = 'DISTANCIEL',
}


export enum WorkType {
  SUR_SITE = 'SUR_SITE',
  HYBRIDE = 'HYBRIDE',
  DISTANCE = 'DISTANCE',
}

export enum StatusPosteRecrutement {
  OUVERT = 'OUVERT',
  EXPIRE = 'EXPIRE',
  FERME = 'FERME',
}
export type InterviewSource = 'LIBRE' | 'CANDIDATURE';
export enum InterviewType {
  RH_FINAL = 'RH_FINAL',
  TECHNIQUE = 'TECHNIQUE',
  RH_INITIAL = 'RH_INITIAL',
 
}
export enum InterviewResult {
  REUSSI = 'REUSSI',
  ECHOUE = 'ECHOUE',
}
export enum InterviewStatus {
  PLANIFIE = 'PLANIFIE',
  CONFIRME = 'CONFIRME',
  EN_COURS = 'EN_COURS',
  TERMINE = 'TERMINE',
  ANNULE = 'ANNULE',
  REPORTE = 'REPORTE',
  ABSENT = 'ABSENT',
}
export enum EtatEntretien {
  RH_ENTRETIEN = 'RH_ENTRETIEN',
  TECHNIQUE_ENTRETIEN = 'TECHNIQUE_ENTRETIEN',
  ACCEPTE = 'ACCEPTE',
  REFUSE_PAR_RH = 'REFUSE_PAR_RH',
  REFUSE_PAR_TECHNIQUE = 'REFUSE_PAR_TECHNIQUE',
}
export enum CvChoice {
  EXISTANT = 'EXISTANT',
  NOUVEAU = 'NOUVEAU',
}
export enum ApplicationStatus {
  EN_ATTENTE='EN_ATTENTE',

  SELECTIONNE='SELECTIONNE',

  EN_ENTRETIEN_RH='EN_ENTRETIEN_RH',

  EN_ENTRETIEN_TECHNIQUE='EN_ENTRETIEN_TECHNIQUE',

  EN_ENTRETIEN_FINAL='EN_ENTRETIEN_FINAL',

  ACCEPTE='ACCEPTE',

  REJETE='REJETE',

  RETIRE='RETIRE',
}